/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import { DOMParser as XmldomParser } from "@xmldom/xmldom";

interface Env {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

if (typeof globalThis.DOMParser === "undefined") {
  // @aws-sdk/xml-builder expects a global DOMParser in Workers validation/runtime.
  globalThis.DOMParser = XmldomParser as unknown as typeof DOMParser;
}

let handlerPromise: Promise<(request: Request) => Promise<Response>> | null = null;

async function getHandler() {
  if (!handlerPromise) {
    handlerPromise = import("../dist/server/index.js").then((mod) => mod.default as (request: Request) => Promise<Response>);
  }
  return handlerPromise;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: async (path) => {
          // If it's an API route, fetch it from the worker itself
          if (path.startsWith('/api/')) {
            const handler = await getHandler();
            const apiRequest = new Request(new URL(path, request.url), request);
            const response = await handler(apiRequest);
            
            // Cloudflare Images binding requires a proper stream or buffer
            // We need to clone it or read it to avoid the "Cannot perform I/O" error
            if (response.ok && response.body) {
              const buffer = await response.arrayBuffer();
              return new Response(buffer, {
                status: response.status,
                headers: response.headers
              });
            }
            return response;
          }
          // Otherwise fetch from ASSETS binding
          return env.ASSETS.fetch(new Request(new URL(path, request.url)));
        },
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Delegate everything else to vinext
    const handler = await getHandler();
    return handler(request);
  },
};
